export const TAG_FETCH_ALL = 'TAG_FETCH_ALL';
export const TAG_FETCH_ALL_FULFILLED = 'TAG_FETCH_ALL_FULFILLED';
export const TAG_FETCH_ALL_FAILED = 'TAG_FETCH_ALL_FAILED';

export const TAG_CREATE = 'TAG_CREATE';
export const TAG_CREATE_FULFILLED = 'TAG_CREATE_FULFILLED';
export const TAG_CREATE_FAILED = 'TAG_CREATE_FAILED';
export const TAG_SEARCH = 'TAG_SEARCH';