export const JOKE_FETCH_WITH_TAG = 'JOKE_FETCH_WITH_TAG';
export const JOKE_FETCH_WITH_TAG_FULFILLED = 'JOKE_FETCH_WITH_TAG_FULFILLED';

export const JOKE_FETCH = 'JOKE_FETCH';
export const JOKE_FETCH_FULFILLED = 'JOKE_FETCH_FULFILLED';
export const JOKE_FETCH_FAILED = 'JOKE_FETCH_FAILED';

export const JOKE_UPDATE = 'JOKE_UPDATE';
export const JOKE_UPDATE_FULFILLED = 'JOKE_UPDATE_FULFILLED';
export const JOKE_UPDATE_FAILED = 'JOKE_UPDATE_FAILED';

export const JOKE_CREATE = 'JOKE_CREATE';
export const JOKE_CREATE_FULFILLED = 'JOKE_CREATE_FULFILLED';
export const JOKE_CREATE_FAILED = 'JOKE_CREATE_FAILED';

export const JOKE_DELETE = 'JOKE_DELETE';
export const JOKE_DELETE_FULFILLED = 'JOKE_DELETE_FULFILLED';
export const JOKE_DELETE_FAILED = 'JOKE_DELETE_FAILED';

export const JOKE_INIT_NEW = 'JOKE_INIT_NEW';
export const JOKE_SEARCH = 'JOKE_SEARCH';